
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADMIRACION ASIGNACION CARACTERES COMA COMENTARIO COMILLA_DOBLE COMILLA_SIMPLE DIFERENTE DIGITO DIVISION ETIQUETA_A ETIQUETA_AUDIO ETIQUETA_B ETIQUETA_BODY ETIQUETA_BUTTON ETIQUETA_CANVAS ETIQUETA_DIV ETIQUETA_DOCTYPE ETIQUETA_FORM ETIQUETA_H ETIQUETA_HEAD ETIQUETA_HR ETIQUETA_HREF ETIQUETA_HTML ETIQUETA_IFRAME ETIQUETA_IMG ETIQUETA_INPUT ETIQUETA_LABEL ETIQUETA_LI ETIQUETA_LINK ETIQUETA_META ETIQUETA_OL ETIQUETA_OPTION ETIQUETA_P ETIQUETA_SCRIPT ETIQUETA_SELECT ETIQUETA_SPAN ETIQUETA_STYLE ETIQUETA_SVG ETIQUETA_TABLE ETIQUETA_TD ETIQUETA_TEXTAREA ETIQUETA_TH ETIQUETA_TITLE ETIQUETA_TR ETIQUETA_UL ETIQUETA_VIDEO GUION_BAJO IGUAL INTERROGACION MAYOR_IGUAL_QUE MAYOR_QUE MENOR_IGUAL_QUE MENOR_QUE MULTIPLICACION PARENTESIS_A PARENTESIS_B PUNTO RESTA SUMAdocumento_html : etiqueta_html contenido_htmletiqueta_html : ETIQUETA_HTMLcontenido_html : contenido_html etiqueta_html\n                      | emptyempty :'
    
_lr_action_items = {'ETIQUETA_HTML':([0,2,3,4,5,6,],[3,-5,-2,3,-4,-3,]),'$end':([1,2,3,4,5,6,],[0,-5,-2,-1,-4,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'documento_html':([0,],[1,]),'etiqueta_html':([0,4,],[2,6,]),'contenido_html':([2,],[4,]),'empty':([2,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> documento_html","S'",1,None,None,None),
  ('documento_html -> etiqueta_html contenido_html','documento_html',2,'p_documento_html','AnalizadorSintactico.py',77),
  ('etiqueta_html -> ETIQUETA_HTML','etiqueta_html',1,'p_etiqueta_html','AnalizadorSintactico.py',81),
  ('contenido_html -> contenido_html etiqueta_html','contenido_html',2,'p_contenido_html','AnalizadorSintactico.py',85),
  ('contenido_html -> empty','contenido_html',1,'p_contenido_html','AnalizadorSintactico.py',86),
  ('empty -> <empty>','empty',0,'p_empty','AnalizadorSintactico.py',93),
]
